#!/bin/bash

MODEL=$(cat /proc/device-tree/model | tr -d '\0')

if [[ $MODEL == *"Raspberry Pi 5"* ]]; then
    #echo "rpi 5"
    GPIO_TOOL=pinctrl
elif [[ $MODEL == *"Raspberry Pi 4 Model B"* ]]; then
    #echo "rpi 4b"
    GPIO_TOOL=raspi-gpio
elif [[ $MODEL == *"Raspberry Pi 3 Model B"* ]]; then
    #echo "rpi 3b"
    GPIO_TOOL=raspi-gpio
else
  echo "unknown model"

fi

BUZZER_GPIO=23

$GPIO_TOOL set $BUZZER_GPIO op

function buzzer_succ () {
    $GPIO_TOOL set $BUZZER_GPIO dh
    sleep 0.1
    $GPIO_TOOL set $BUZZER_GPIO dl
    sleep 0.1
}

function buzzer_fail () {
    for((i=0;i<3;i++)); do
        $GPIO_TOOL set $BUZZER_GPIO dh
        sleep 0.1
        $GPIO_TOOL set $BUZZER_GPIO dl
        sleep 0.1
    done

}


buzzer_fail
